#!/bin/bash

function createFarmer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/farmer.auto.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/farmer.auto.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-farmer --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-farmer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-farmer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-farmer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-farmer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/farmer.auto.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy farmer's CA cert to farmer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/farmer.auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/farmer.auto.com/msp/tlscacerts/ca.crt"

  # Copy farmer's CA cert to farmer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/farmer.auto.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/farmer.auto.com/tlsca/tlsca.farmer.auto.com-cert.pem"

  # Copy farmer's CA cert to farmer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/farmer.auto.com/ca"
  cp "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/farmer.auto.com/ca/ca.farmer.auto.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-farmer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-farmer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-farmer --id.name farmeradmin --id.secret farmeradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-farmer -M "${PWD}/organizations/peerOrganizations/farmer.auto.com/peers/peer0.farmer.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/farmer.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/farmer.auto.com/peers/peer0.farmer.auto.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-farmer -M "${PWD}/organizations/peerOrganizations/farmer.auto.com/peers/peer0.farmer.auto.com/tls" --enrollment.profile tls --csr.hosts peer0.farmer.auto.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/farmer.auto.com/peers/peer0.farmer.auto.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/farmer.auto.com/peers/peer0.farmer.auto.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/farmer.auto.com/peers/peer0.farmer.auto.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/farmer.auto.com/peers/peer0.farmer.auto.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/farmer.auto.com/peers/peer0.farmer.auto.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/farmer.auto.com/peers/peer0.farmer.auto.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-farmer -M "${PWD}/organizations/peerOrganizations/farmer.auto.com/users/User1@farmer.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/farmer.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/farmer.auto.com/users/User1@farmer.auto.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://farmeradmin:farmeradminpw@localhost:7054 --caname ca-farmer -M "${PWD}/organizations/peerOrganizations/farmer.auto.com/users/Admin@farmer.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/farmer.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/farmer.auto.com/users/Admin@farmer.auto.com/msp/config.yaml"
}

function createDistributor() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/distributor.auto.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/distributor.auto.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-distributor --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-distributor.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-distributor.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-distributor.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-distributor.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/distributor.auto.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy distributor's CA cert to distributor's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/distributor.auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/distributor.auto.com/msp/tlscacerts/ca.crt"

  # Copy distributor's CA cert to distributor's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/distributor.auto.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/distributor.auto.com/tlsca/tlsca.distributor.auto.com-cert.pem"

  # Copy distributor's CA cert to distributor's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/distributor.auto.com/ca"
  cp "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/distributor.auto.com/ca/ca.distributor.auto.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-distributor --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-distributor --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-distributor --id.name distributoradmin --id.secret distributoradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-distributor -M "${PWD}/organizations/peerOrganizations/distributor.auto.com/peers/peer0.distributor.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/distributor.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/distributor.auto.com/peers/peer0.distributor.auto.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-distributor -M "${PWD}/organizations/peerOrganizations/distributor.auto.com/peers/peer0.distributor.auto.com/tls" --enrollment.profile tls --csr.hosts peer0.distributor.auto.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/distributor.auto.com/peers/peer0.distributor.auto.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/distributor.auto.com/peers/peer0.distributor.auto.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/distributor.auto.com/peers/peer0.distributor.auto.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/distributor.auto.com/peers/peer0.distributor.auto.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/distributor.auto.com/peers/peer0.distributor.auto.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/distributor.auto.com/peers/peer0.distributor.auto.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-distributor -M "${PWD}/organizations/peerOrganizations/distributor.auto.com/users/User1@distributor.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/distributor.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/distributor.auto.com/users/User1@distributor.auto.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://distributoradmin:distributoradminpw@localhost:8054 --caname ca-distributor -M "${PWD}/organizations/peerOrganizations/distributor.auto.com/users/Admin@distributor.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/distributor/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/distributor.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/distributor.auto.com/users/Admin@distributor.auto.com/msp/config.yaml"
}


function createRetailer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/retailer.auto.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/retailer.auto.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-retailer --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-retailer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-retailer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-retailer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-retailer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/retailer.auto.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy retailer's CA cert to retailer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/retailer.auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/retailer.auto.com/msp/tlscacerts/ca.crt"

  # Copy retailer's CA cert to retailer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/retailer.auto.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/retailer.auto.com/tlsca/tlsca.retailer.auto.com-cert.pem"

  # Copy retailer's CA cert to retailer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/retailer.auto.com/ca"
  cp "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/retailer.auto.com/ca/ca.retailer.auto.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-retailer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-retailer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-retailer --id.name retaileradmin --id.secret retaileradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/retailer.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/tls" --enrollment.profile tls --csr.hosts peer0.retailer.auto.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.auto.com/users/User1@retailer.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/retailer.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/retailer.auto.com/users/User1@retailer.auto.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://retaileradmin:retaileradminpw@localhost:11054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.auto.com/users/Admin@retailer.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/retailer.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/retailer.auto.com/users/Admin@retailer.auto.com/msp/config.yaml"
}

# function createRetailer() {
#   echo "Enrolling the CA admin"
#   mkdir -p organizations/peerOrganizations/retailer.auto.com/

#   export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/retailer.auto.com/

#   set -x
#   fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-retailer --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
#   { set +x; } 2>/dev/null

#   echo 'NodeOUs:
#   Enable: true
#   ClientOUIdentifier:
#     Certificate: cacerts/localhost-8054-ca-retailer.pem
#     OrganizationalUnitIdentifier: client
#   PeerOUIdentifier:
#     Certificate: cacerts/localhost-8054-ca-retailer.pem
#     OrganizationalUnitIdentifier: peer
#   AdminOUIdentifier:
#     Certificate: cacerts/localhost-8054-ca-retailer.pem
#     OrganizationalUnitIdentifier: admin
#   OrdererOUIdentifier:
#     Certificate: cacerts/localhost-8054-ca-retailer.pem
#     OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/retailer.auto.com/msp/config.yaml"

#   # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

#   # Copy retailer's CA cert to retailer's /msp/tlscacerts directory (for use in the channel MSP definition)
#   mkdir -p "${PWD}/organizations/peerOrganizations/retailer.auto.com/msp/tlscacerts"
#   cp "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/retailer.auto.com/msp/tlscacerts/ca.crt"

#   # Copy retailer's CA cert to retailer's /tlsca directory (for use by clients)
#   mkdir -p "${PWD}/organizations/peerOrganizations/retailer.auto.com/tlsca"
#   cp "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/retailer.auto.com/tlsca/tlsca.retailer.auto.com-cert.pem"

#   # Copy retailer's CA cert to retailer's /ca directory (for use by clients)
#   mkdir -p "${PWD}/organizations/peerOrganizations/retailer.auto.com/ca"
#   cp "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/retailer.auto.com/ca/ca.retailer.auto.com-cert.pem"

#   echo "Registering peer0"
#   set -x
#   fabric-ca-client register --caname ca-retailer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
#   { set +x; } 2>/dev/null

#   echo "Registering user"
#   set -x
#   fabric-ca-client register --caname ca-retailer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
#   { set +x; } 2>/dev/null

#   echo "Registering the org admin"
#   set -x
#   fabric-ca-client register --caname ca-retailer --id.name retaileradmin --id.secret retaileradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
#   { set +x; } 2>/dev/null

#   echo "Generating the peer0 msp"
#   set -x
#   fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
#   { set +x; } 2>/dev/null

#   cp "${PWD}/organizations/peerOrganizations/retailer.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/msp/config.yaml"

#   echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
#   set -x
#   fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/tls" --enrollment.profile tls --csr.hosts peer0.retailer.auto.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
#   { set +x; } 2>/dev/null

#   # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
#   cp "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/tls/ca.crt"
#   cp "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/tls/server.crt"
#   cp "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/retailer.auto.com/peers/peer0.retailer.auto.com/tls/server.key"

#   echo "Generating the user msp"
#   set -x
#   fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.auto.com/users/User1@retailer.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
#   { set +x; } 2>/dev/null

#   cp "${PWD}/organizations/peerOrganizations/retailer.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/retailer.auto.com/users/User1@retailer.auto.com/msp/config.yaml"

#   echo "Generating the org admin msp"
#   set -x
#   fabric-ca-client enroll -u https://retaileradmin:retaileradminpw@localhost:8054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.auto.com/users/Admin@retailer.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/retailer/ca-cert.pem"
#   { set +x; } 2>/dev/null

#   cp "${PWD}/organizations/peerOrganizations/retailer.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/retailer.auto.com/users/Admin@retailer.auto.com/msp/config.yaml"
# }


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/auto.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/auto.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/auto.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/auto.com/msp/tlscacerts/tlsca.auto.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/auto.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/auto.com/tlsca/tlsca.auto.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/auto.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls" --enrollment.profile tls --csr.hosts orderer.auto.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp/tlscacerts/tlsca.auto.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/auto.com/users/Admin@auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/auto.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/auto.com/users/Admin@auto.com/msp/config.yaml"
}

createFarmer
createDistributor
createRetailer
createOrderer
